DROP INDEX IF EXISTS notifications_user_unread_idx;
ALTER TABLE notifications DROP COLUMN IF EXISTS read_at;
DELETE FROM notifications WHERE type IN ('SUPPORT_REQUEST','SUPPORT_REQUEST_RECEIVED','CONTRIBUTION_REVIEW_REMINDER') OR channel='IN_APP';
ALTER TABLE notifications DROP CONSTRAINT notifications_channel_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_channel_check CHECK (channel IN ('EMAIL'));
ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (type IN ('ACCOUNT_CREATED','CONTRIBUTION_DUE','CONTRIBUTION_OVERDUE','PROOF_SUBMITTED','CONTRIBUTION_APPROVED','CONTRIBUTION_REJECTED','ASSISTANCE_REQUESTED','ASSISTANCE_APPROVED','ASSISTANCE_REJECTED','ASSISTANCE_PAID'));
